// ============================================================
// ATECO 2025 - Sezione C: Attivita manifatturiere
// Fonte: Struttura ufficiale ATECO 2025 (ISTAT), 13/03/2025.
// 24 divisioni (10-33) + 403 sottocategorie a 6 cifre.
// Usato dal Simulatore 1 per confermare il requisito R1 (sezione C).
// ============================================================
var ATECO_C_DIVISIONI = [
    { c: "10", t: "Produzione di prodotti alimentari" },
    { c: "11", t: "Produzione di bevande" },
    { c: "12", t: "Produzione di prodotti del tabacco" },
    { c: "13", t: "Fabbricazione di tessili" },
    { c: "14", t: "Fabbricazione di articoli di abbigliamento" },
    { c: "15", t: "Fabbricazione di pelli e cuoi e articoli in pelle e simili di altri materiali" },
    { c: "16", t: "Produzione e lavorazione del legno e dei prodotti a base di legno e sughero," },
    { c: "17", t: "Fabbricazione di carta e di prodotti di carta" },
    { c: "18", t: "Stampa e riproduzione di supporti registrati" },
    { c: "19", t: "Fabbricazione di coke e prodotti derivanti dalla raffinazione del petrolio" },
    { c: "20", t: "Fabbricazione di prodotti chimici" },
    { c: "21", t: "Fabbricazione di prodotti farmaceutici di base e di preparati farmaceutici" },
    { c: "22", t: "Fabbricazione di prodotti in gomma e in materie plastiche" },
    { c: "23", t: "Fabbricazione di altri prodotti della lavorazione di minerali non metalliferi" },
    { c: "24", t: "Fabbricazione di metalli di base" },
    { c: "25", t: "Fabbricazione di prodotti in metallo, esclusi macchinari e attrezzature" },
    { c: "26", t: "Fabbricazione di computer e prodotti di elettronica e ottica" },
    { c: "27", t: "Fabbricazione di apparecchiature elettriche" },
    { c: "28", t: "Fabbricazione di macchinari e apparecchiature n.c.a." },
    { c: "29", t: "Fabbricazione di autoveicoli, rimorchi e semirimorchi" },
    { c: "30", t: "Fabbricazione di altri mezzi di trasporto" },
    { c: "31", t: "Fabbricazione di mobili" },
    { c: "32", t: "Altre attività manifatturiere" },
    { c: "33", t: "Riparazione, manutenzione e installazione di macchine e apparecchiature" },
];
var ATECO_C = [
    { c: "10.11.00", t: "Lavorazione e conservazione di carne, esclusa la carne di volatili" },
    { c: "10.12.00", t: "Lavorazione e conservazione di carne di volatili" },
    { c: "10.13.00", t: "Produzione di prodotti a base di carne, inclusi prodotti a base di carne di volatili" },
    { c: "10.20.01", t: "Lavorazione di alghe" },
    { c: "10.20.09", t: "Altre attività di lavorazione e conservazione di pesce, crostacei e molluschi" },
    { c: "10.31.00", t: "Lavorazione e conservazione di patate" },
    { c: "10.32.00", t: "Produzione di succhi a base di frutta e ortaggi" },
    { c: "10.39.00", t: "Altre attività di lavorazione e conservazione di frutta e ortaggi" },
    { c: "10.41.10", t: "Produzione di olio di oliva" },
    { c: "10.41.20", t: "Produzione di altri oli vegetali" },
    { c: "10.41.30", t: "Produzione di oli e grassi animali" },
    { c: "10.42.00", t: "Produzione di margarina e di grassi alimentari simili" },
    { c: "10.51.10", t: "Trattamento igienico del latte" },
    { c: "10.51.20", t: "Produzione di derivati del latte" },
    { c: "10.52.00", t: "Produzione di gelati" },
    { c: "10.61.11", t: "Lavorazione di frumento" },
    { c: "10.61.19", t: "Lavorazione di altri cereali" },
    { c: "10.61.20", t: "Lavorazione del riso" },
    { c: "10.61.90", t: "Lavorazioni di altre granaglie" },
    { c: "10.62.00", t: "Produzione di amidi e di prodotti amidacei" },
    { c: "10.71.10", t: "Produzione di pane e prodotti di panetteria simili" },
    { c: "10.71.20", t: "Produzione di prodotti di pasticceria freschi" },
    { c: "10.72.00", t: "Produzione di fette biscottate, biscotti, prodotti di pasticceria conservati" },
    { c: "10.73.01", t: "Produzione di prodotti farinacei freschi" },
    { c: "10.73.02", t: "Produzione di prodotti farinacei conservati" },
    { c: "10.81.00", t: "Produzione di zucchero" },
    { c: "10.82.00", t: "Produzione di cacao, cioccolato, caramelle e confetterie" },
    { c: "10.83.01", t: "Lavorazione di tè e di altri preparati per infusi" },
    { c: "10.83.02", t: "Lavorazione di caffè" },
    { c: "10.84.00", t: "Produzione di condimenti e spezie" },
    { c: "10.85.01", t: "Produzione di pasti e piatti preparati a base di carne, inclusi pasti e piatti preparati a base di carne di volatili" },
    { c: "10.85.02", t: "Produzione di pasti e piatti preparati a base di pesce" },
    { c: "10.85.03", t: "Produzione di pasti e piatti preparati a base di ortaggi" },
    { c: "10.85.04", t: "Produzione di pizza surgelata o altrimenti conservata" },
    { c: "10.85.05", t: "Produzione di pasti e piatti preparati a base di pasta" },
    { c: "10.85.09", t: "Produzione di altri pasti e piatti preparati" },
    { c: "10.86.00", t: "Produzione di preparati omogeneizzati e di alimenti dietetici" },
    { c: "10.89.01", t: "Produzione di integratori alimentari" },
    { c: "10.89.09", t: "Produzione di altri prodotti alimentari vari n.c.a." },
    { c: "10.91.00", t: "Produzione di mangimi per l'alimentazione degli animali da allevamento" },
    { c: "10.92.00", t: "Produzione di prodotti per l'alimentazione degli animali da compagnia" },
    { c: "11.01.00", t: "Distillazione, rettifica e miscelatura di alcolici" },
    { c: "11.02.10", t: "Produzione di vini, esclusi vini spumanti e altri vini speciali" },
    { c: "11.02.20", t: "Produzione di vini spumanti e altri vini speciali" },
    { c: "11.03.00", t: "Produzione di sidro e di altre bevande fermentate a base di frutta" },
    { c: "11.04.00", t: "Produzione di altre bevande fermentate non distillate" },
    { c: "11.05.00", t: "Produzione di birra" },
    { c: "11.06.00", t: "Produzione di malto" },
    { c: "11.07.01", t: "Produzione di bibite analcoliche" },
    { c: "11.07.02", t: "Produzione di acque in bottiglia" },
    { c: "12.00.00", t: "Produzione di prodotti del tabacco" },
    { c: "13.10.00", t: "Preparazione e filatura di fibre tessili" },
    { c: "13.20.00", t: "Tessitura" },
    { c: "13.30.00", t: "Finissaggio dei tessili" },
    { c: "13.91.00", t: "Fabbricazione di tessuti a maglia e all'uncinetto" },
    { c: "13.92.10", t: "Fabbricazione di tessili per la casa" },
    { c: "13.92.20", t: "Fabbricazione di tessili per l'arredo" },
    { c: "13.93.00", t: "Fabbricazione di tappeti e moquette" },
    { c: "13.94.00", t: "Fabbricazione di spago, corde, funi e reti" },
    { c: "13.95.00", t: "Fabbricazione di tessuti non-tessuti e di articoli in tessuto non-tessuto" },
    { c: "13.96.00", t: "Fabbricazione di altri tessuti per uso tecnico e industriale" },
    { c: "13.99.10", t: "Fabbricazione di ricami, tulle, pizzi e merletti" },
    { c: "13.99.90", t: "Fabbricazione di feltro e altri prodotti tessili diversi n.c.a." },
    { c: "14.10.10", t: "Fabbricazione di articoli di calzetteria a maglia e all'uncinetto" },
    { c: "14.10.20", t: "Fabbricazione di maglioni e altri articoli a maglia e all'uncinetto" },
    { c: "14.21.10", t: "Fabbricazione in serie di abbigliamento esterno" },
    { c: "14.21.20", t: "Sartoria e confezione su misura di abbigliamento esterno" },
    { c: "14.22.00", t: "Fabbricazione di biancheria intima" },
    { c: "14.23.00", t: "Fabbricazione di indumenti da lavoro" },
    { c: "14.24.00", t: "Fabbricazione di abbigliamento in pelle e in pelliccia" },
    { c: "14.29.00", t: "Fabbricazione di altri articoli di abbigliamento e accessori n.c.a." },
    { c: "15.11.00", t: "Concia, tintura e rifinizione di pelli, cuoi e pellicce" },
    { c: "15.12.00", t: "Fabbricazione di articoli da viaggio, borse, pelletteria e selleria di qualsiasi materiale" },
    { c: "15.20.10", t: "Fabbricazione di calzature, escluse parti in cuoio per calzature" },
    { c: "15.20.20", t: "Fabbricazione di parti in cuoio per calzature" },
    { c: "16.11.00", t: "Taglio e piallatura del legno" },
    { c: "16.12.00", t: "Lavorazione e finitura del legno" },
    { c: "16.21.00", t: "Fabbricazione di fogli da impiallacciatura e di pannelli a base di legno" },
    { c: "16.22.00", t: "Fabbricazione di pavimenti di legno con elementi pre-assemblati" },
    { c: "16.23.01", t: "Fabbricazione di stand e strutture simili in legno per convegni e fiere" },
    { c: "16.23.09", t: "Fabbricazione di altri prodotti di carpenteria in legno e falegnameria per l'edilizia n.c.a." },
    { c: "16.24.00", t: "Fabbricazione di imballaggi in legno" },
    { c: "16.25.00", t: "Fabbricazione di porte e finestre in legno" },
    { c: "16.26.00", t: "Produzione di combustibili solidi da biomassa vegetale" },
    { c: "16.27.00", t: "Finitura di prodotti in legno" },
    { c: "16.28.11", t: "Fabbricazione di cornici" },
    { c: "16.28.19", t: "Fabbricazione di altri prodotti in legno n.c.a." },
    { c: "16.28.20", t: "Fabbricazione di articoli in sughero" },
    { c: "16.28.30", t: "Fabbricazione di articoli in paglia e materiali da intreccio" },
    { c: "17.11.00", t: "Fabbricazione di pasta-carta" },
    { c: "17.12.00", t: "Fabbricazione di carta e cartone" },
    { c: "17.21.00", t: "Fabbricazione di carta, cartone ondulato e di imballaggi di carta e cartone" },
    { c: "17.22.00", t: "Fabbricazione di prodotti igienico-sanitari e per uso domestico in carta e ovatta di cellulosa" },
    { c: "17.23.01", t: "Fabbricazione di prodotti cartotecnici scolastici e commerciali" },
    { c: "17.23.09", t: "Fabbricazione di altri prodotti cartotecnici" },
    { c: "17.24.00", t: "Fabbricazione di carta da parati" },
    { c: "17.25.00", t: "Fabbricazione di altri articoli di carta e cartone" },
    { c: "18.11.00", t: "Stampa di giornali" },
    { c: "18.12.00", t: "Altra stampa" },
    { c: "18.13.00", t: "Lavorazioni preliminari alla stampa e ai media" },
    { c: "18.14.00", t: "Legatoria e servizi connessi" },
    { c: "18.20.00", t: "Riproduzione di supporti registrati" },
    { c: "19.10.00", t: "Fabbricazione di prodotti di cokeria" },
    { c: "19.20.10", t: "Raffinazione di petrolio" },
    { c: "19.20.20", t: "Fabbricazione di derivati del petrolio" },
    { c: "19.20.30", t: "Miscelazione di gas petroliferi liquefatti (GPL) e loro imbottigliamento" },
    { c: "19.20.40", t: "Fabbricazione di prodotti di base per la copertura stradale" },
    { c: "19.20.90", t: "Fabbricazione di altri prodotti derivanti dalla raffinazione del petrolio e prodotti da combustibili fossili" },
    { c: "20.11.00", t: "Fabbricazione di gas industriali" },
    { c: "20.12.00", t: "Fabbricazione di coloranti e pigmenti" },
    { c: "20.13.00", t: "Fabbricazione di altri prodotti chimici di base inorganici" },
    { c: "20.14.00", t: "Fabbricazione di altri prodotti chimici di base organici" },
    { c: "20.15.00", t: "Fabbricazione di fertilizzanti e composti azotati" },
    { c: "20.16.00", t: "Fabbricazione di materie plastiche in forme primarie" },
    { c: "20.17.00", t: "Fabbricazione di gomma sintetica in forme primarie" },
    { c: "20.20.00", t: "Fabbricazione di fitofarmaci, disinfettanti e altri prodotti chimici per l'agricoltura" },
    { c: "20.30.00", t: "Fabbricazione di pitture, vernici e smalti, inchiostri da stampa e adesivi sintetici" },
    { c: "20.41.10", t: "Fabbricazione di saponi, detergenti e preparazioni tensioattive" },
    { c: "20.41.20", t: "Fabbricazione di glicerina e altri prodotti per la pulizia e la lucidatura" },
    { c: "20.42.00", t: "Fabbricazione di profumi e cosmetici" },
    { c: "20.51.00", t: "Produzione di biocarburanti liquidi" },
    { c: "20.59.11", t: "Fabbricazione di fiammiferi" },
    { c: "20.59.12", t: "Fabbricazione di articoli esplosivi" },
    { c: "20.59.20", t: "Fabbricazione di colle" },
    { c: "20.59.30", t: "Fabbricazione di oli essenziali" },
    { c: "20.59.91", t: "Fabbricazione di liquidi per inalazione per sigarette elettroniche" },
    { c: "20.59.99", t: "Fabbricazione di tutti gli altri prodotti chimici vari n.c.a." },
    { c: "20.60.00", t: "Fabbricazione di fibre sintetiche e artificiali" },
    { c: "21.10.00", t: "Fabbricazione di prodotti farmaceutici di base" },
    { c: "21.20.01", t: "Fabbricazione di sostanze diagnostiche radioattive in vivo" },
    { c: "21.20.09", t: "Fabbricazione di medicinali e altri preparati farmaceutici" },
    { c: "22.11.10", t: "Fabbricazione di pneumatici e camere d'aria" },
    { c: "22.11.20", t: "Rigenerazione e ricostruzione di pneumatici" },
    { c: "22.12.00", t: "Fabbricazione di altri prodotti in gomma" },
    { c: "22.21.00", t: "Fabbricazione di lastre, fogli, tubi e profilati in materie plastiche" },
    { c: "22.22.00", t: "Fabbricazione di imballaggi in materie plastiche" },
    { c: "22.23.00", t: "Fabbricazione di porte e finestre in materie plastiche" },
    { c: "22.24.01", t: "Fabbricazione di rivestimenti per pareti e pavimenti in materie plastiche" },
    { c: "22.24.09", t: "Fabbricazione di altri articoli in materie plastiche per l'edilizia" },
    { c: "22.25.00", t: "Lavorazione e finitura di prodotti in materie plastiche" },
    { c: "22.26.11", t: "Fabbricazione di articoli e attrezzature per la pulizia per uso domestico in materie plastiche" },
    { c: "22.26.12", t: "Fabbricazione di articoli e attrezzature per la pulizia per uso non domestico in materie plastiche" },
    { c: "22.26.91", t: "Fabbricazione di articoli per l'ufficio e la scuola in materie plastiche" },
    { c: "22.26.99", t: "Fabbricazione di altri prodotti vari in materie plastiche n.c.a." },
    { c: "23.11.00", t: "Fabbricazione di vetro piano" },
    { c: "23.12.00", t: "Lavorazione e trasformazione del vetro piano" },
    { c: "23.13.00", t: "Fabbricazione di vetro cavo" },
    { c: "23.14.00", t: "Fabbricazione di fibre di vetro" },
    { c: "23.15.10", t: "Lavorazione di vetro a mano e a soffio artistico" },
    { c: "23.15.90", t: "Altre attività di fabbricazione e lavorazione di altro vetro incluso il vetro per usi tecnici" },
    { c: "23.20.00", t: "Fabbricazione di prodotti refrattari" },
    { c: "23.31.00", t: "Fabbricazione di piastrelle in ceramica per pavimenti e rivestimenti" },
    { c: "23.32.00", t: "Fabbricazione di mattoni, tegole e altri prodotti per l'edilizia in terracotta" },
    { c: "23.41.00", t: "Fabbricazione di prodotti in ceramica per usi domestici e ornamentali" },
    { c: "23.42.00", t: "Fabbricazione di articoli sanitari in ceramica" },
    { c: "23.43.00", t: "Fabbricazione di isolatori e di pezzi isolanti in ceramica" },
    { c: "23.44.00", t: "Fabbricazione di altri prodotti in ceramica per uso tecnico e industriale" },
    { c: "23.45.00", t: "Fabbricazione di altri prodotti in ceramica" },
    { c: "23.51.00", t: "Produzione di cemento" },
    { c: "23.52.10", t: "Produzione di calce" },
    { c: "23.52.20", t: "Produzione di gesso" },
    { c: "23.61.01", t: "Fabbricazione di tubi prefabbricati in calcestruzzo per acqua potabile" },
    { c: "23.61.02", t: "Fabbricazione di caminetti prefabbricati in calcestruzzo" },
    { c: "23.61.03", t: "Fabbricazione di elementi prefabbricati in calcestruzzo per l'edilizia" },
    { c: "23.61.04", t: "Fabbricazione di strutture prefabbricate in calcestruzzo per l'edilizia" },
    { c: "23.61.09", t: "Fabbricazione di prodotti in calcestruzzo per l'edilizia n.c.a." },
    { c: "23.62.00", t: "Fabbricazione di prodotti in gesso per l'edilizia" },
    { c: "23.63.00", t: "Produzione di calcestruzzo pronto per l'uso" },
    { c: "23.64.00", t: "Produzione di malta" },
    { c: "23.65.01", t: "Fabbricazione di prodotti in sostanze vegetali agglomerate con cemento, gesso o altri leganti minerali" },
    { c: "23.65.02", t: "Fabbricazione di prodotti in asbesto-cemento o cellulosa fibrocemento" },
    { c: "23.66.01", t: "Fabbricazione di statue, bassorilievi e altorilievi, vasi e fioriere" },
    { c: "23.66.09", t: "Fabbricazione di altri prodotti in calcestruzzo, cemento e gesso n.c.a." },
    { c: "23.70.10", t: "Taglio e lavorazione di pietre e di marmo" },
    { c: "23.70.20", t: "Lavorazione artistica di marmo e di altre pietre affini" },
    { c: "23.70.30", t: "Frantumazione di pietre" },
    { c: "23.91.00", t: "Fabbricazione di prodotti abrasivi" },
    { c: "23.99.00", t: "Fabbricazione di altri prodotti in minerali non metalliferi n.c.a." },
    { c: "24.10.00", t: "Fabbricazione di ferro, acciaio e ferroleghe" },
    { c: "24.20.10", t: "Fabbricazione di tubi, condotti, profilati cavi non saldati e relativi raccordi in acciaio" },
    { c: "24.20.20", t: "Fabbricazione di tubi, condotti, profilati cavi saldati e relativi raccordi in acciaio" },
    { c: "24.31.00", t: "Trafilatura a freddo di barre" },
    { c: "24.32.00", t: "Laminazione a freddo di nastri" },
    { c: "24.33.01", t: "Profilatura mediante formatura o piegatura a freddo di profilati aperti e lamiere grecate" },
    { c: "24.33.02", t: "Profilatura mediante formatura o piegatura a freddo di pannelli stratificati" },
    { c: "24.33.03", t: "Presagomatura dell'acciaio per cemento armato e attività simili" },
    { c: "24.34.00", t: "Trafilatura a freddo di fili" },
    { c: "24.41.00", t: "Produzione di metalli preziosi" },
    { c: "24.42.00", t: "Produzione di alluminio" },
    { c: "24.43.00", t: "Produzione di piombo, zinco e stagno" },
    { c: "24.44.00", t: "Produzione di rame" },
    { c: "24.45.00", t: "Produzione di altri metalli non ferrosi" },
    { c: "24.46.00", t: "Trattamento di combustibili nucleari" },
    { c: "24.51.01", t: "Fusione di getti in ghisa grigia o lamellare" },
    { c: "24.51.02", t: "Fusione di getti in ghisa duttile" },
    { c: "24.51.09", t: "Fusione di getti in ghisa n.c.a." },
    { c: "24.52.00", t: "Fusione di getti in acciaio" },
    { c: "24.53.01", t: "Fusione di getti in alluminio" },
    { c: "24.53.02", t: "Fusione di getti in magnesio" },
    { c: "24.53.03", t: "Fusione di getti in superleghe a base cobalto" },
    { c: "24.53.09", t: "Fusione di getti in metalli leggeri n.c.a." },
    { c: "24.54.01", t: "Fusione di getti in rame" },
    { c: "24.54.02", t: "Fusione di getti in zinco" },
    { c: "24.54.03", t: "Fusione di getti in nichel" },
    { c: "24.54.09", t: "Fusione di getti in altri metalli non ferrosi n.c.a." },
    { c: "25.11.00", t: "Fabbricazione di strutture metalliche e di parti di strutture metalliche" },
    { c: "25.12.10", t: "Fabbricazione di porte, finestre e loro telai, imposte e cancelli in metallo" },
    { c: "25.12.20", t: "Fabbricazione di tende in metallo e prodotti simili" },
    { c: "25.21.10", t: "Fabbricazione di radiatori e contenitori in metallo per caldaie per il riscaldamento centrale" },
    { c: "25.21.20", t: "Fabbricazione di generatori di vapore" },
    { c: "25.22.00", t: "Fabbricazione di altre cisterne, serbatoi e contenitori in metallo" },
    { c: "25.30.10", t: "Fabbricazione di armi e munizioni per uso militare" },
    { c: "25.30.20", t: "Fabbricazione di armi e munizioni per uso sportivo e civile" },
    { c: "25.40.00", t: "Fucinatura e formatura dei metalli e metallurgia delle polveri" },
    { c: "25.51.00", t: "Rivestimento dei metalli" },
    { c: "25.52.00", t: "Trattamento termico dei metalli" },
    { c: "25.53.00", t: "Lavori di meccanica generale dei metalli" },
    { c: "25.61.00", t: "Fabbricazione di articoli di coltelleria e posateria" },
    { c: "25.62.00", t: "Fabbricazione di serrature e cerniere" },
    { c: "25.63.11", t: "Fabbricazione di utensileria ad azionamento manuale" },
    { c: "25.63.12", t: "Fabbricazione di parti intercambiabili per macchine utensili" },
    { c: "25.63.20", t: "Fabbricazione di stampi, portastampi, sagome, forme per macchine" },
    { c: "25.91.00", t: "Fabbricazione di bidoni in acciaio e di contenitori simili" },
    { c: "25.92.00", t: "Fabbricazione di imballaggi in metallo leggero" },
    { c: "25.93.10", t: "Fabbricazione di prodotti fabbricati con fili metallici" },
    { c: "25.93.20", t: "Fabbricazione di catene" },
    { c: "25.93.30", t: "Fabbricazione di molle" },
    { c: "25.94.00", t: "Fabbricazione di articoli di bulloneria" },
    { c: "25.99.10", t: "Fabbricazione di articoli domestici in metallo per la cucina e le stanze da bagno" },
    { c: "25.99.20", t: "Fabbricazione di casseforti, cassette di sicurezza e porte metalliche blindate" },
    { c: "25.99.90", t: "Fabbricazione di altri prodotti vari in metallo n.c.a." },
    { c: "26.11.00", t: "Fabbricazione di componenti elettronici" },
    { c: "26.12.00", t: "Fabbricazione di schede elettroniche integrate" },
    { c: "26.20.00", t: "Fabbricazione di computer e unità periferiche" },
    { c: "26.30.01", t: "Fabbricazione di apparecchiature trasmittenti radiotelevisive" },
    { c: "26.30.09", t: "Fabbricazione di altre apparecchiature per le comunicazioni" },
    { c: "26.40.01", t: "Fabbricazione di console per videogiochi" },
    { c: "26.40.09", t: "Fabbricazione di altri prodotti di elettronica di consumo" },
    { c: "26.51.10", t: "Fabbricazione di strumenti per navigazione, idrologia, geofisica e meteorologia" },
    { c: "26.51.21", t: "Fabbricazione di sistemi antifurto e antincendio" },
    { c: "26.51.29", t: "Fabbricazione di altri strumenti e apparecchi di misurazione e prova n.c.a." },
    { c: "26.52.00", t: "Fabbricazione di orologi" },
    { c: "26.60.01", t: "Fabbricazione di apparecchiature per irradiazione, elettromedicali ed elettroterapeutiche per usi medici" },
    { c: "26.60.02", t: "Fabbricazione di apparecchiature per irradiazione, elettromedicali ed elettroterapeutiche per usi non medici" },
    { c: "26.70.11", t: "Fabbricazione di strumenti ottici e strumenti ottici di precisione" },
    { c: "26.70.12", t: "Fabbricazione di strumenti ottici di misurazione e controllo" },
    { c: "26.70.20", t: "Fabbricazione di supporti magnetici e ottici" },
    { c: "26.70.30", t: "Fabbricazione di apparecchiature fotografiche" },
    { c: "27.11.00", t: "Fabbricazione di motori, generatori e trasformatori elettrici" },
    { c: "27.12.00", t: "Fabbricazione di apparecchiature per la distribuzione e il controllo dell'elettricità" },
    { c: "27.20.00", t: "Fabbricazione di batterie e accumulatori" },
    { c: "27.31.00", t: "Fabbricazione di cavi in fibra ottica" },
    { c: "27.32.00", t: "Fabbricazione di altri fili e cavi elettronici ed elettrici" },
    { c: "27.33.00", t: "Fabbricazione di attrezzature per cablaggio" },
    { c: "27.40.01", t: "Fabbricazione di apparecchiature per l'illuminazione per mezzi di trasporto" },
    { c: "27.40.02", t: "Fabbricazione di luminarie per feste" },
    { c: "27.40.09", t: "Fabbricazione di altre apparecchiature per l'illuminazione" },
    { c: "27.51.00", t: "Fabbricazione di elettrodomestici" },
    { c: "27.52.00", t: "Fabbricazione di apparecchi non elettrici per uso domestico" },
    { c: "27.90.01", t: "Fabbricazione di apparecchiature elettriche per saldatura e brasatura" },
    { c: "27.90.02", t: "Fabbricazione di insegne elettriche e apparecchiature elettriche di segnalazione" },
    { c: "27.90.03", t: "Fabbricazione di capacitori, resistenze, condensatori elettrici e simili" },
    { c: "27.90.04", t: "Fabbricazione di apparecchiature elettriche per parrucchieri, solarium e centri estetici" },
    { c: "27.90.09", t: "Fabbricazione di altre apparecchiature elettriche n.c.a." },
    { c: "28.11.10", t: "Fabbricazione di motori, esclusi motori per aeromobili, veicoli e motocicli" },
    { c: "28.11.20", t: "Fabbricazione di turbine" },
    { c: "28.12.00", t: "Fabbricazione di apparecchiature fluidodinamiche" },
    { c: "28.13.00", t: "Fabbricazione di altre pompe e compressori" },
    { c: "28.14.00", t: "Fabbricazione di altri rubinetti e valvole" },
    { c: "28.15.00", t: "Fabbricazione di cuscinetti, ingranaggi e organi di trasmissione" },
    { c: "28.21.10", t: "Fabbricazione di forni" },
    { c: "28.21.20", t: "Fabbricazione di caldaie e apparecchiature fisse per il riscaldamento domestico" },
    { c: "28.22.01", t: "Fabbricazione di ascensori, scale mobili e tappeti mobili" },
    { c: "28.22.09", t: "Fabbricazione di altri apparecchi di sollevamento e movimentazione" },
    { c: "28.23.00", t: "Fabbricazione di macchine e attrezzature per ufficio, esclusi computer e unità periferiche" },
    { c: "28.24.00", t: "Fabbricazione di utensili portatili a motore" },
    { c: "28.25.00", t: "Fabbricazione di apparecchiature di climatizzazione per uso non domestico" },
    { c: "28.29.10", t: "Fabbricazione di bilance e distributori automatici" },
    { c: "28.29.20", t: "Fabbricazione di impianti di distillazione o rettificazione per raffinerie di petrolio e industrie chimiche" },
    { c: "28.29.30", t: "Fabbricazione di macchine per la dosatura, la confezione e per l'imballaggio" },
    { c: "28.29.41", t: "Fabbricazione di macchine per la pulizia di pavimenti, superfici e ambienti per uso non domestico" },
    { c: "28.29.49", t: "Fabbricazione di altre macchine per la pulizia per uso non domestico" },
    { c: "28.29.91", t: "Fabbricazione di apparecchi per depurare e filtrare liquidi" },
    { c: "28.29.92", t: "Fabbricazione di livelle, metri doppi a nastro e utensili simili, strumenti di precisione per meccanica" },
    { c: "28.29.99", t: "Fabbricazione di altre macchine varie di impiego generale n.c.a." },
    { c: "28.30.10", t: "Fabbricazione di trattori per l'agricoltura e la silvicoltura" },
    { c: "28.30.91", t: "Fabbricazione di macchine per il giardinaggio e la cura del verde" },
    { c: "28.30.99", t: "Fabbricazione di altre macchine per l'agricoltura e la silvicoltura n.c.a." },
    { c: "28.41.00", t: "Fabbricazione di macchine per la deformazione dei metalli e di altre macchine utensili per la lavorazione dei" },
    { c: "28.42.00", t: "Fabbricazione di altre macchine utensili" },
    { c: "28.91.00", t: "Fabbricazione di macchine per la metallurgia" },
    { c: "28.92.00", t: "Fabbricazione di macchine da miniera, cava e cantiere" },
    { c: "28.93.00", t: "Fabbricazione di macchine per l'industria alimentare, delle bevande e del tabacco" },
    { c: "28.94.10", t: "Fabbricazione di macchine tessili" },
    { c: "28.94.20", t: "Fabbricazione di macchine per la lavorazione delle pelli e del cuoio" },
    { c: "28.94.30", t: "Fabbricazione di macchine per lavanderie e stirerie" },
    { c: "28.95.00", t: "Fabbricazione di macchine per l'industria della carta e del cartone" },
    { c: "28.96.00", t: "Fabbricazione di macchine per l'industria delle materie plastiche e della gomma" },
    { c: "28.97.01", t: "Fabbricazione di macchine per la produzione additiva per deposizione di materiali metallici" },
    { c: "28.97.02", t: "Fabbricazione di macchine per la produzione additiva per deposizione di materie plastiche o di gomma" },
    { c: "28.97.09", t: "Fabbricazione di macchine per la produzione additiva n.c.a." },
    { c: "28.99.10", t: "Fabbricazione di macchine per la stampa e la legatoria" },
    { c: "28.99.20", t: "Fabbricazione di robot industriali con compiti multipli per scopi speciali" },
    { c: "28.99.91", t: "Fabbricazione di apparecchiature per il lancio di aeromobili, catapulte per portaerei e relative attrezzature" },
    { c: "28.99.92", t: "Fabbricazione di giostre, altalene e altre attrazioni di divertimento" },
    { c: "28.99.93", t: "Fabbricazione di apparecchiature per l'allineamento e il bilanciamento delle ruote e altre apparecchiature" },
    { c: "28.99.99", t: "Fabbricazione di tutte le altre macchine varie per impieghi speciali n.c.a." },
    { c: "29.10.00", t: "Fabbricazione di autoveicoli" },
    { c: "29.20.00", t: "Fabbricazione di carrozzerie per autoveicoli; fabbricazione di rimorchi e semirimorchi" },
    { c: "29.31.00", t: "Fabbricazione di apparecchiature elettriche ed elettroniche per autoveicoli" },
    { c: "29.32.00", t: "Fabbricazione di altre parti e accessori per autoveicoli" },
    { c: "30.11.00", t: "Costruzione di navi e di strutture galleggianti per scopi civili" },
    { c: "30.12.00", t: "Costruzione di imbarcazioni da diporto e sportive" },
    { c: "30.13.00", t: "Costruzione di navi e imbarcazioni per scopi militari" },
    { c: "30.20.00", t: "Costruzione di locomotive e di materiale rotabile ferro-tranviario" },
    { c: "30.31.00", t: "Fabbricazione di aeromobili, veicoli spaziali e relativi equipaggiamenti per scopi civili" },
    { c: "30.32.00", t: "Fabbricazione di aeromobili, veicoli spaziali e relativi equipaggiamenti per scopi militari" },
    { c: "30.40.00", t: "Fabbricazione di veicoli militari da combattimento" },
    { c: "30.91.11", t: "Fabbricazione di motori per motocicli" },
    { c: "30.91.12", t: "Fabbricazione di motocicli, esclusi motori" },
    { c: "30.91.20", t: "Fabbricazione di parti e accessori per motocicli" },
    { c: "30.92.10", t: "Fabbricazione di biciclette, escluse parti e accessori" },
    { c: "30.92.20", t: "Fabbricazione di parti e accessori per biciclette" },
    { c: "30.92.30", t: "Fabbricazione di veicoli per disabili" },
    { c: "30.92.40", t: "Fabbricazione di carrozzine e passeggini" },
    { c: "30.99.00", t: "Fabbricazione di altri mezzi di trasporto n.c.a." },
    { c: "31.00.11", t: "Fabbricazione di moduli dedicati al comfort acustico per negozi, uffici e altri spazi per collettività" },
    { c: "31.00.12", t: "Fabbricazione di sedie e poltrone per negozi" },
    { c: "31.00.13", t: "Fabbricazione di altri mobili per negozi" },
    { c: "31.00.14", t: "Fabbricazione di sedie e poltrone per uffici e altri spazi per collettività" },
    { c: "31.00.15", t: "Fabbricazione di altri mobili per uffici e altri spazi per collettività" },
    { c: "31.00.20", t: "Fabbricazione di mobili da cucina" },
    { c: "31.00.31", t: "Fabbricazione di mobili per arredo interno, esclusi mobili da cucina, sedie, divani e prodotti simili" },
    { c: "31.00.32", t: "Fabbricazione di mobili per arredo esterno" },
    { c: "31.00.33", t: "Fabbricazione di sedie e sedili" },
    { c: "31.00.34", t: "Fabbricazione di divani, divani letto e poltrone" },
    { c: "31.00.35", t: "Fabbricazione di materassi" },
    { c: "31.00.36", t: "Fabbricazione di parti e accessori di mobili" },
    { c: "31.00.37", t: "Finitura di mobili" },
    { c: "31.00.39", t: "Fabbricazione di altri mobili n.c.a." },
    { c: "32.11.00", t: "Coniazione di monete" },
    { c: "32.12.10", t: "Lavorazione di pietre preziose e semipreziose" },
    { c: "32.12.20", t: "Fabbricazione di gioielli e articoli di oreficeria in metalli preziosi" },
    { c: "32.13.00", t: "Fabbricazione di bigiotteria e articoli simili" },
    { c: "32.20.00", t: "Fabbricazione di strumenti musicali" },
    { c: "32.30.01", t: "Fabbricazione di attrezzature da palestra, per centri di fitness e per atletica" },
    { c: "32.30.09", t: "Fabbricazione di altri articoli sportivi" },
    { c: "32.40.10", t: "Fabbricazione di giochi" },
    { c: "32.40.20", t: "Fabbricazione di giocattoli" },
    { c: "32.50.10", t: "Fabbricazione di protesi dentarie" },
    { c: "32.50.20", t: "Fabbricazione di altre protesi e ausili" },
    { c: "32.50.30", t: "Fabbricazione di lenti oftalmiche" },
    { c: "32.50.40", t: "Fabbricazione di montature per occhiali" },
    { c: "32.50.51", t: "Fabbricazione di strumenti e apparecchiature mediche e dentistiche" },
    { c: "32.50.52", t: "Fabbricazione di forniture mediche e dentistiche" },
    { c: "32.50.53", t: "Fabbricazione di mobili per uso medico e dentistico" },
    { c: "32.91.00", t: "Fabbricazione di scope e spazzole" },
    { c: "32.99.10", t: "Fabbricazione di dispositivi protettivi di sicurezza" },
    { c: "32.99.20", t: "Fabbricazione di ombrelli, bottoni, chiusure lampo, parrucche e affini" },
    { c: "32.99.30", t: "Fabbricazione di articoli di cancelleria" },
    { c: "32.99.40", t: "Fabbricazione di casse funebri" },
    { c: "32.99.91", t: "Fabbricazione di sigarette elettroniche" },
    { c: "32.99.99", t: "Fabbricazione di altri articoli vari n.c.a." },
    { c: "33.11.01", t: "Riparazione e manutenzione di cisterne, serbatoi e contenitori in metallo" },
    { c: "33.11.02", t: "Riparazione e manutenzione di utensileria ad azionamento manuale" },
    { c: "33.11.03", t: "Riparazione e manutenzione di stampi, portastampi, sagome, forme per macchine" },
    { c: "33.11.04", t: "Riparazione e manutenzione di casseforti, cassette di sicurezza, porte metalliche blindate" },
    { c: "33.11.05", t: "Riparazione e manutenzione di armi da fuoco militari, di ordinanza e artiglieria" },
    { c: "33.11.06", t: "Riparazione e manutenzione di armi per uso sportivo e civile" },
    { c: "33.11.09", t: "Riparazione e manutenzione di altri prodotti in metallo" },
    { c: "33.12.10", t: "Riparazione e manutenzione di motori, turbine, pompe, compressori e altri elementi simili" },
    { c: "33.12.20", t: "Riparazione e manutenzione di caldaie per processi industriali" },
    { c: "33.12.30", t: "Riparazione e manutenzione di apparecchi di sollevamento e movimentazione" },
    { c: "33.12.40", t: "Riparazione e manutenzione di impianti di refrigerazione industriale e di depurazione dell'aria" },
    { c: "33.12.51", t: "Riparazione e manutenzione di macchine e attrezzature per ufficio" },
    { c: "33.12.52", t: "Riparazione e manutenzione di bilance e distributori automatici" },
    { c: "33.12.53", t: "Riparazione e manutenzione di impianti di distillazione o rettificazione per raffinerie di petrolio e industrie" },
    { c: "33.12.54", t: "Riparazione e manutenzione di macchine per impacchettare e imballare" },
    { c: "33.12.59", t: "Riparazione e manutenzione di altre macchine di impiego generale n.c.a." },
    { c: "33.12.60", t: "Riparazione e manutenzione di trattori agricoli" },
    { c: "33.12.70", t: "Riparazione e manutenzione di altre macchine per l'agricoltura e la silvicoltura" },
    { c: "33.12.91", t: "Affilatura di lame e seghe per macchinari" },
    { c: "33.12.92", t: "Riparazione e manutenzione di giostre, altalene e altre attrazioni di divertimento" },
    { c: "33.12.99", t: "Riparazione e manutenzione di altre macchine per impieghi speciali n.c.a." },
    { c: "33.13.01", t: "Riparazione e manutenzione di apparecchiature per irradiazione, elettromedicali ed elettroterapeutiche" },
    { c: "33.13.02", t: "Riparazione e manutenzione di strumenti e apparecchiature ottiche" },
    { c: "33.13.09", t: "Riparazione e manutenzione di altre apparecchiature elettroniche e ottiche" },
    { c: "33.14.00", t: "Riparazione e manutenzione di apparecchiature elettriche" },
    { c: "33.15.00", t: "Riparazione e manutenzione di navi e imbarcazioni per scopi civili" },
    { c: "33.16.00", t: "Riparazione e manutenzione di aeromobili e veicoli spaziali per scopi civili" },
    { c: "33.17.00", t: "Riparazione e manutenzione di altri mezzi di trasporto per scopi civili" },
    { c: "33.18.10", t: "Riparazione e manutenzione di veicoli da combattimento per scopi militari" },
    { c: "33.18.20", t: "Riparazione e manutenzione di navi e imbarcazioni per scopi militari" },
    { c: "33.18.30", t: "Riparazione e manutenzione di aeromobili e veicoli spaziali per scopi militari" },
    { c: "33.19.00", t: "Riparazione e manutenzione di altre apparecchiature" },
    { c: "33.20.01", t: "Installazione di motori, generatori e trasformatori elettrici e di apparecchiature per la distribuzione e il" },
    { c: "33.20.02", t: "Installazione di apparecchiature per le comunicazioni e di apparecchiature radiotelevisive" },
    { c: "33.20.03", t: "Installazione di strumenti e apparecchi di misurazione e controllo" },
    { c: "33.20.04", t: "Installazione di cisterne, serbatoi e contenitori in metallo" },
    { c: "33.20.05", t: "Installazione di generatori di vapore" },
    { c: "33.20.06", t: "Installazione di macchinari e attrezzature per ufficio" },
    { c: "33.20.07", t: "Installazione di strumenti e apparecchiature mediche e dentistiche" },
    { c: "33.20.09", t: "Installazione di altre macchine e apparecchiature industriali" },
];
if (typeof window !== 'undefined') { window.ATECO_C = ATECO_C; window.ATECO_C_DIVISIONI = ATECO_C_DIVISIONI; }
