// ============================================================
// Fondo Contrasto Deindustrializzazione 2026
// Elenco ufficiale dei Comuni dei due Consorzi (brief, sez. 5.3 e 5.4).
// DPCM 19 maggio 2025, art. 3, c. 1, lett. a) e gli elenchi dei Consorzi.
// 153 comuni (123 Lazio in 5 raggruppamenti + 30 Piceno).
// ============================================================

var COMUNI = [
    // Consorzio Industriale del Lazio - Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)
    { nome: "Acquafondata", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Aquino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Atina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Ausonia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Belmonte Castello", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Casalvieri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Cassino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Castelnuovo Parano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Castrocielo", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Cervaro", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Colfelice", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Colle San Magno", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Coreno Ausonio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Esperia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Gallinaro", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Picinisco", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Pico", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Piedimonte San Germano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Pignataro Interamna", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Pontecorvo", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Roccasecca", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Sant'Ambrogio sul Garigliano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "San Giorgio a Liri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "San Giovanni Incarico", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "San Vittore del Lazio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Sant'Andrea del Garigliano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Sant'Apollinare", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Sant'Elia Fiumerapido", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Settefrati", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Terelle", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Vallemaio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Vallerotonda", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Villa Latina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Villa Santa Lucia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Acquapendente", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Bagnoregio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Barbarano Romano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Bassano Romano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Bolsena", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Celleno", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Valentano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Vetralla", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Villa San Giovanni in Tuscia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Tarquinia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Montalto di Castro", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    { nome: "Canino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 1 · ex Consorzio Lazio Meridionale (COSILAM)" },
    // Consorzio Industriale del Lazio - Punto 2 · ex Consorzio Sud Pontino
    { nome: "Campodimele", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Castelforte", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Fondi", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Formia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Gaeta", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Itri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Lenola", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Minturno", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Monte San Biagio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Sperlonga", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Spigno Saturnia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Santi Cosma e Damiano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    { nome: "Viterbo", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 2 · ex Consorzio Sud Pontino" },
    // Consorzio Industriale del Lazio - Punto 3 · ex Consorzio Roma-Latina
    { nome: "Aprilia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Cisterna di Latina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Cave", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Civitavecchia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Lanuvio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Latina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Pomezia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Pontinia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Roma Capitale", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Sabaudia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Sermoneta", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Sezze", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Sonnino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Tolfa", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    { nome: "Velletri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 3 · ex Consorzio Roma-Latina" },
    // Consorzio Industriale del Lazio - Punto 4 · ex Consorzio di Frosinone
    { nome: "Alatri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Anagni", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Arpino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Broccostella", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Ceccano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Ceprano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Falvaterra", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Ferentino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Fontana Liri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Frosinone", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Guarcino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Isola del Liri", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Monte San Giovanni Campano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Morolo", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Pastena", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Patrica", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Pofi", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Ripi", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Sora", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Supino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Torre Cajetani", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Veroli", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Vico nel Lazio", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Colleferro", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Montefiascone", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    { nome: "Capranica", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 4 · ex Consorzio di Frosinone" },
    // Consorzio Industriale del Lazio - Punto 5 · ex Consorzio Provincia di Rieti
    { nome: "Amatrice", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Borgorose", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Canepina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Caprarola", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Castel Sant'Elia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Cittaducale", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Civita Castellana", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Corchiano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Fabrica di Roma", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Fara in Sabina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Frasso Sabino", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Gallese", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Magliano Sabina", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Montelibretti", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Nepi", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Orte", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Pescorocchiano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Poggio Moiano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Poggio Nativo", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Rieti", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Scandriglia", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Vallerano", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    { nome: "Vignanello", consorzio: "Consorzio Industriale del Lazio", raggruppamento: "Punto 5 · ex Consorzio Provincia di Rieti" },
    // Piceno Consind (Valli del Tronto, dell'Aso e del Tesino) - Provincia di Ascoli Piceno
    { nome: "Acquasanta Terme", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Acquaviva Picena", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Appignano del Tronto", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Arquata del Tronto", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Ascoli Piceno", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Carassai", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Castel di Lama", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Castignano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Castorano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Colli del Tronto", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Comunanza", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Cossignano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Folignano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Force", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Grottammare", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Maltignano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Monsampolo del Tronto", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Montalto delle Marche", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Montedinove", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Montegallo", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Montemonaco", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Monteprandone", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Offida", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Palmiano", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Ripatransone", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Roccafluvione", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Rotella", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "San Benedetto del Tronto", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Spinetoli", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
    { nome: "Venarotta", consorzio: "Piceno Consind (Valli del Tronto, dell'Aso e del Tesino)", raggruppamento: "Provincia di Ascoli Piceno" },
];
if (typeof window !== 'undefined') { window.COMUNI = COMUNI; }
